import {
  TRIP_ID,
  type CategoryId,
  type PackingItem,
} from "../app/trips/packing-data";

// Transcribed from the owner's final Canvas on September 25, 2026.
const rows: [CategoryId, string, number | null, string, boolean][] = [
  ["lake", "Cooler", 1, "large cooler", true],
  ["lake", "Ice or frozen packs", null, "enough to fill cooler", false],
  ["lake", "Drinking water or gatorade", null, "case / refill jugs", false],
  ["lake", "Other drinks", null, "group preference", false],
  ["lake", "Picnic blankets", 2, "blankets", false],
  ["lake", "Donut floatee", 1, "set", true],
  ["lake", "Ball", 1, "item", true],
  ["lake", "Sunscreen", 1, "bottle", false],
  ["lake", "Insect repellent", 1, "bottle", false],
  ["lake", "First-aid supplies", 1, "kit", false],
  ["food", "Car and lake snacks (Bucees run)", null, "for five people", false],
  ["food", "Trash bags", null, "5 bags", true],
  ["food", "Paper towels and napkins", 1, "supply", false],
  ["games", "Playing cards and Poker set", 1, "deck", true],
  ["games", "Group games (Exploding Kittens)", 2, "games", false],
  ["games", "Speaker and charger", 1, "set", false],
  ["ssam", "Boneless meat", 3.5, "lb raw", false],
  ["ssam", "Lettuce or wrap leaves", 2, "large heads", false],
  ["ssam", "Perilla leaves", 1, "pack", false],
  ["ssam", "Rice", 2.5, "cups dry", false],
  ["ssam", "Ssamjang", 1, "tub", false],
  ["ssam", "Kimchi", 1, "container", false],
  ["ssam", "Garlic", 1, "pack / bulb", false],
  ["ssam", "Green chilies", 1, "pack", false],
  ["ssam", "Grilling vegetables", null, "for five people", false],
  ["ssam", "Sesame oil", 1, "bottle", false],
  ["ssam", "Salt and pepper", 1, "set", false],
  ["ssam", "Marinade", 1, "bottle", false],
  ["ssam", "Cooking oil", 1, "bottle", false],
  ["ssam", "Dessert or late-night snack", null, "hehe", false],
  ["cooking", "Usable grill", 1, "grill", false],
  ["cooking", "Correct grill fuel", null, "enough for dinner", false],
  ["cooking", "Grill tongs", 2, "set", false],
  [
    "cooking",
    "Rice cooker or lidded pot (unless we're doing instant rice)",
    1,
    "item",
    false,
  ],
  ["cooking", "Disposable chopsticks", 5, "sets", false],
  ["cooking", "Dish soap and sponge", 1, "set", false],
];

export const initialItems: PackingItem[] = rows.map(
  ([category, name, quantity, unit, packed], index) => ({
    id: `26a05710-0926-4260-8001-${String(index + 1).padStart(12, "0")}`,
    trip_id: TRIP_ID,
    category,
    name,
    quantity,
    unit,
    packed,
    deleted: false,
    version: 1,
    position: index,
  }),
);
